name: taskhamster
description: "Taskhamster Kiosk WebView App"
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.16.0
  wakelock_plus: ^1.2.8
  screen_brightness: ^2.1.7
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.3
  flutter_dotenv: ^6.0.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
