name: taskhamster
description: "Enterprise Kiosk System for Taskhamster tablets."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Standard iOS ikoner
  cupertino_icons: ^1.0.8

  # --- KIOSK FUNKSJONALITET ---

  # Holder CPU og Skjerm vÃ¥ken
  wakelock_plus: ^1.2.8

  # Gir tilgang til maskinvarens lysstyrke (Versjonen terminalen din foreslo)
  screen_brightness: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter-regler
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true